name: 'Update Release Body'
description: 'Updates the body of a given release'
inputs:
  owner: # id of input
    description: '(string) The account owner of the repository. The name is not case sensitive.'
    required: true
  repo:
    description: '(string) The name of the repository without the .git extension. The name is not case sensitive.'
    required: true
  release_id:
    description: '(integer) The unique identifier of the release.'
    required: true
  tag_name:
    description: '(string) The name of the tag.'
    required: true
  target_commitish:
    description: '(string) Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.'
  body:
    description: '(string) Text describing the contents of the tag.'
    required: false
  body_path:
    description: '(markdown file) Path to file with information about the tag.'
    required: false
  draft:
    description: '(bool) true makes the release a draft, and false publishes the release.'
    required: false
  prerelease:
    description: '(bool) true to identify the release as a prerelease, false to identify the release as a full release.'
    required: false
  make_latest:
    description: (string) Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to true for newly published releases. legacy specifies that the latest release should be determined based on the release creation date and higher semantic version.
    required: false
  discussion_category_name:
    description: '(string) If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. If there is already a discussion linked to the release, this parameter is ignored.'
    required: false
outputs:
  message:
    description: '(string) A message indicating the success/failure of the action.'
runs:
  using: 'node16'
  main: 'update-release.js'
